server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    instance-id: user-providor-instance
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
    prefer-ip-address: true
    hostname: user-providor-host
spring:
  application:
    name: user-providor

